// Migration files land here as <14-digit-UTC-timestamp>_<TypeName>.swift,
// generated by `swift run migrate create <TypeName>`. Non-digit-prefixed
// files like this one are ignored by the discovery plugin.
