#!/usr/bin/env bash
#
# Regenerates Sources/flight/EmbeddedTemplates.swift from templates/.
#
# The CLI ships the templates inside its binary: once installed, there is no
# repository beside it to read from. Embedding them means `flight new` emits
# byte-for-byte what CI/verify-templates.sh builds and tests — the generator
# and the thing it generates cannot disagree, because one is derived from the
# other and CI checks the derivation is current.
#
#   ./CI/generate-embedded-templates.sh          # write
#   ./CI/generate-embedded-templates.sh --check  # fail if stale
#
set -euo pipefail
cd "$(dirname "$0")/.."

out="Sources/flight/EmbeddedTemplates.swift"
tmp="$(mktemp)"
trap 'rm -f "$tmp" "$tmp.files"' EXIT

# Enumerated from git, not the filesystem: a file that is ignored locally —
# .vscode/, an editor backup, a stray build artifact — would otherwise be
# embedded on one machine and absent on another, and the --check in CI would
# report the committed file as stale for a reason nobody could see.
#
# An untracked file under templates/ is therefore *silently skipped*, which
# is a trap: adding a new template file and regenerating produces a binary
# that emits a project missing it, and the failure surfaces three steps later
# as "cannot find type X in scope" inside a generated project. Refuse instead.
untracked="$(git ls-files --others --exclude-standard templates)"
if [ -n "$untracked" ]; then
  echo "::error::untracked files under templates/ would be silently omitted:" >&2
  echo "$untracked" | sed 's/^/  /' >&2
  echo "git add them, then regenerate." >&2
  exit 1
fi

git ls-files templates > "$tmp.files"

python3 - "$tmp" "$tmp.files" <<'PY'
import pathlib, sys

out = pathlib.Path(sys.argv[1])
root = pathlib.Path("templates")
tracked = {
    line.strip() for line in pathlib.Path(sys.argv[2]).read_text().splitlines() if line.strip()
}

def swift_literal(text: str) -> str:
    # A raw string with enough pounds that the content cannot terminate it.
    pounds = "#"
    while pounds + '"""' in text or '"""' + pounds in text:
        pounds += "#"
    return f'{pounds}"""\n{text}\n"""{pounds}'

lines = [
    # Generated, and mostly other people's source quoted verbatim — linting it
    # would report thousands of violations in code this file does not own.
    "// swift-format-ignore-file",
    "// Generated by CI/generate-embedded-templates.sh. Do not edit.",
    "//",
    "// Every file of every template, embedded so an installed binary carries",
    "// the projects it emits. Regenerate after changing anything in templates/.",
    "",
    "enum EmbeddedTemplates {",
    "    /// tier -> (relative path -> file contents)",
    "    static let files: [String: [String: String]] = [",
]

for tier in sorted(p.name for p in root.iterdir() if p.is_dir()):
    lines.append(f'        "{tier}": [')
    tier_root = root / tier
    for f in sorted(tier_root.rglob("*")):
        if not f.is_file() or f.as_posix() not in tracked:
            continue
        rel = f.relative_to(tier_root).as_posix()
        if rel == "Package.resolved":
            continue
        text = f.read_text()
        lines.append(f'            "{rel}": {swift_literal(text)},')
    lines.append("        ],")

lines += ["    ]", "", "    static var tiers: [String] { files.keys.sorted() }", "}", ""]
out.write_text("\n".join(lines))
PY

if [ "${1:-}" = "--check" ]; then
  if diff -q "$tmp" "$out" >/dev/null 2>&1; then
    echo "✔ embedded templates are current"
  else
    echo "::error::Sources/flight/EmbeddedTemplates.swift is stale."
    echo "::error::Run ./CI/generate-embedded-templates.sh and commit the result."
    diff "$out" "$tmp" | head -20 || true
    exit 1
  fi
else
  mv "$tmp" "$out"
  trap - EXIT
  echo "wrote $out ($(wc -l < "$out") lines)"
fi
